### ISSUE TITLE
New functionality ivar: Create script for p-value strand bias for ivar

### ISSUE THREAD

**Issue by saramonzon** [BU-ISCIII/viralrecon#1]
Modify ivar_variants_to_vcf.py in order to add strand-bias p-value functionality:
https://github.com/BU-ISCIII/viralrecon/blob/master/bin/ivar_variants_to_vcf.py

**Comment by ErikaKvalem** [comment]
Implemented. I have tried it on sample 214826 introducing modification to force p<0.05. Lacking testing other samples that contain strand bias

**Comment by saramonzon** [comment]
New functionality already included in viralrecon here https://github.com/nf-core/viralrecon/pull/258
