### ISSUE TITLE
Fix Bcftools masking reference name

### ISSUE THREAD

**Issue by ErikaKvalem** [BU-ISCIII/viralrecon#12]

**Comment by ErikaKvalem** [comment]
``"""
    awk -v OFS='\\t' '{print \$1, \$2-1, \$2, \$4}' ${mpileup[0]} | awk '\$4 < $params.min_coverage' > ${prefix}.lowcov.bed
    parse_mask_bed.py ${vcf[0]} ${prefix}.lowcov.bed ${prefix}.lowcov.fix.bed
    bedtools merge -i ${prefix}.lowcov.fix.bed > ${prefix}.mask.bed
    bedtools maskfasta \\
        -fi $fasta \\
        -bed ${prefix}.mask.bed \\
        -fo ${index_base}.ref.masked.fa
    cat ${index_base}.ref.masked.fa | bcftools consensus ${vcf[0]} > ${prefix}.consensus.masked.fa
    header=\$(head -n 1 ${prefix}.consensus.masked.fa | sed 's/>//g')
    sed -i "s/\${header}/${sample}/g" ${prefix}.consensus.masked.fa
    plot_base_density.r --fasta_files ${prefix}.consensus.masked.fa --prefixes $prefix --output_dir ./

**Comment by ErikaKvalem** [comment]
"""
    awk -v OFS='\\t' '{print \$1, \$2-1, \$2, \$4}' ${mpileup[0]} | awk '\$4 < $params.min_coverage' > ${prefix}.lowcov.bed

    parse_mask_bed.py ${vcf[0]} ${prefix}.lowcov.bed ${prefix}.lowcov.fix.bed

    bedtools merge -i ${prefix}.lowcov.fix.bed > ${prefix}.mask.bed

    bedtools maskfasta \\
        -fi $fasta \\
        -bed ${prefix}.mask.bed \\
        -fo ${index_base}.ref.masked.fa

    cat ${index_base}.ref.masked.fa | bcftools consensus ${vcf[0]} > ${prefix}.consensus.masked.fa

    header=\$(head -n 1 ${prefix}.consensus.masked.fa | sed 's/>//g')
    sed -i "s/\${header}/${sample}/g" ${prefix}.consensus.masked.fa

    plot_base_density.r --fasta_files ${prefix}.consensus.masked.fa --prefixes $prefix --output_dir ./

**Comment by saramonzon** [comment]
This has been fixed in viralrecon here https://github.com/nf-core/viralrecon/pull/255 and here https://github.com/nf-core/viralrecon/pull/259
