### ISSUE TITLE
New functionality ivar: fix annotation for complete codons variants

### ISSUE THREAD

**Issue by saramonzon** [BU-ISCIII/viralrecon#3]

**Comment by ErikaKvalem** [comment]
I have the script working, however I have to include it in a function and optimize the code. I also have to upload it to github

**Comment by ErikaKvalem** [comment]
Updated here e21db8f489950943f2ef080a1219d26692c326df

Added new functionality to check for double or triple consecutive positions and check if they belong to the same codon. 
It remains to add the functionality to check the last lines

**Comment by ErikaKvalem** [comment]
I added here eb8d2ac016ddd0a8bb466bb09163d5fa756a6a1a functionality for checking last lines, I just realized I should also check if the last lines are consecutive and same codon etc. I will do it in the next version

**Comment by saramonzon** [comment]
The new functionlity has been included in viralrecon https://github.com/nf-core/viralrecon/pull/258
