### ISSUE TITLE
Convert Rscript for long and wide table to python and add ivar and bcftools support

### ISSUE THREAD

**Issue by saramonzon** [BU-ISCIII/viralrecon#4]

**Comment by ErikaKvalem** [comment]
First version working. Improve code. We have checked the differences between Ivar, Varscan, & Bcftools

**Comment by ErikaKvalem** [comment]
Bcftools, we have discovered the lineages are not correct because the consensus are not created properly. A new issue was opened concerning lineages and fasta  masking

**Comment by ErikaKvalem** [comment]
The scipt is working and I have tried to optimized it as much as I could. 
Pending to upload to github

**Comment by ErikaKvalem** [comment]
Code here e5a255cd6369d31e9d2666452d2a3d7f4b8ac171
