### ISSUE TITLE
General stats comparison variants all and >80/75%

### ISSUE THREAD

**Issue by saramonzon** [BU-ISCIII/viralrecon#5]

**Comment by Alema91** [comment]
1. Unificate gff annotations between programs.
2. **Total variants**
-  Table creation with all the data.
- Basic statistics (Allele frequency, GENE and EFFECT)
- Linages comprobation of variants
3. **Unique variants**
- Table creation
- Visualizate and classification using bam and IGV
- Statistics
4. **Special variants**
- Download specific variants of all linages to compare with three programs
- Calculate some False Positives comparing between variant callers.
