### ISSUE TITLE
Consensus comparison between bcftools, varscan and ivar consensus

### ISSUE THREAD

**Issue by saramonzon** [BU-ISCIII/viralrecon#6]

**Comment by Alema91** [comment]
Continue with the validation.

**Comment by Alema91** [comment]
I have obtained the unique variant of each program and now I have to verify these variants in the .bam files in order to record them.

**Comment by Alema91** [comment]
1. Analyse the narrow differences between samples with ANI and N% indexes.
2. Visualizate the variants in ivar consensus. Program ideas?
